#!/bin/sh

# Adds ticket before commit message, parsed from branch with name like XXX-1234_some_desc
# Should be placed in ${project.dir}/.git/hooks/prepare-commit-msg

NAME=$(git branch | grep '*' | sed 's/* //' | sed 's/_.*//') 
DESCRIPTION=$(git config branch."$NAME".description)

echo "$NAME"': '$(cat "$1") > "$1"
if [ -n "$DESCRIPTION" ] 
then
   echo "" >> "$1"
   echo $DESCRIPTION >> "$1"
fi 
