#!/bin/sh

# Adds ticket before commit message, parsed from branch with name like XXX-1234_some_desc

NAME=$(git branch | grep '*' | sed 's/* //' | sed 's/_.*//')

START=$(cat $1 | cut -c 1-3)
# PLA is a start of the ticket name, to avoid duplication on amends
if [ "$START" != "PLA" ]
then
        echo "$NAME"': '$(cat "$1") > "$1"
fi
